CREATE TABLE IF NOT EXISTS "role" (
    "id" SERIAL NOT NULL PRIMARY KEY,
	"name" CHARACTER VARYING(255) NOT NULL UNIQUE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "tariff" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" CHARACTER VARYING(255) NOT NULL UNIQUE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "user" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "name" CHARACTER VARYING(100) NOT NULL,
    "last_name" CHARACTER VARYING(100) NOT NULL,
    "middle_name" CHARACTER VARYING(100),
    "email" CHARACTER VARYING(255) NOT NULL UNIQUE,
    "phone" CHARACTER VARYING(11) NOT NULL UNIQUE,
    "password" CHARACTER VARYING(255) NOT NULL,
	"tariff_id" INTEGER REFERENCES "tariff" ON UPDATE CASCADE ON DELETE SET NULL,
	"inn" CHARACTER VARYING(12),
	"snils" CHARACTER VARYING(11) NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "service" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "employee" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"name" CHARACTER VARYING(100) NOT NULL,
    "last_name" CHARACTER VARYING(100) NOT NULL,
    "middle_name" CHARACTER VARYING(100),
    "email" CHARACTER VARYING(255) NOT NULL UNIQUE,
    "password" CHARACTER VARYING(255) NOT NULL,
	"role_id" INTEGER REFERENCES "role" ON UPDATE CASCADE ON DELETE SET NULL,
	"active" BOOLEAN NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "employee_specs" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"employee_id" BIGINT NOT NULL REFERENCES "employee" ON UPDATE CASCADE ON DELETE CASCADE,
	"service_id" INTEGER NOT NULL REFERENCES "service" ON UPDATE CASCADE ON DELETE CASCADE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	UNIQUE ("employee_id", "service_id")
);

CREATE TABLE IF NOT EXISTS "request" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"name" CHARACTER VARYING(255) NOT NULL,
	"service_id" INTEGER REFERENCES "service" ON UPDATE CASCADE ON DELETE SET NULL,
	"owner_id" BIGINT NOT NULL REFERENCES "employee" ON UPDATE CASCADE ON DELETE CASCADE,
	"employee_id" BIGINT REFERENCES "employee" ON UPDATE CASCADE ON DELETE SET NULL,
	"priority" SMALLINT NOT NULL,
	"desc" TEXT NOT NULL,
	"status" SMALLINT NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"desired_at" TIMESTAMPTZ NOT NULL,
	"closed_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "setting" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "default_tariff_id" INT REFERENCES "tariff" ON UPDATE CASCADE ON DELETE SET NULL,
    "superuser_role_id" INT REFERENCES "role" ON UPDATE CASCADE ON DELETE SET NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);
--
-- DO $$
-- BEGIN
--     IF NOT EXISTS (SELECT 1 FROM tariff) THEN
--         INSERT INTO tariff ("name") VALUES ('Бесплатный');
-- END IF;
-- END $$;
--
-- DO $$
-- BEGIN
--     IF NOT EXISTS (SELECT 1 FROM role) THEN
--         INSERT INTO role ("name") VALUES ('Администратор');
-- END IF;
-- END $$;